// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtggxsohghrqqgoiowpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0Z2d4c29oZ2hycXFnb2lvd3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzMyNzIsImV4cCI6MjA3MTU0OTI3Mn0.8O_0MIQH7ZYoMM2ADeHtQX9dgPZbOq_TxrL9AXXqvP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});